const marketplaceRequests = [
  {
    "id_hash": "A07GL33b",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": false,
    "created_at": "6 days ago",
    "description": "This I’ll ashk sh shhah drs vishdhni hgfkv deekh SHG",
    "request_details": null,
    "status": "approved",
    "service_type": "General Marketing Services",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": false,
    "is_deal_closed": false,
    "slug": "A07GL33b"
  },
  {
    "id_hash": "instagram-food-finance-business-tamil-urdu-9e1391f9ee7a418b8c1efb8a94d6b61a",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": false,
    "created_at": "2 weeks ago",
    "description": "Kjdnlkqne ckeiwqehiwqehiqwdcqwjedqkwjenfiwquefdqiewpfqjfdc",
    "status": "approved",
    "service_type": "Talent Management Agencies",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": false,
    "is_deal_closed": false,
    "slug": "instagram food finance business tamil urdu 9e1391f9",
    "request_details": {
      "cities": ["Bengaluru"],
      "followers_range": {"ig_followers_min": "10k", "ig_followers_max": "50k"},
      "categories": ["Food", "Finance & Business"],
      "languages": ["Tamil", "Urdu"],
      "platform": ["Instagram"]
    },
  },
  {
    "id_hash": "instagram-finance & business-photographers-videographers-adoni-adyar-9e138f9d2e8a4285bc41581d3e2697b3",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": false,
    "created_at": "2 weeks ago",
    "description": "Ldkaslkdflsmdclskdmoijfqkwenfqiwenfqoifdnlsadmclkascd",
    "request_details": {
      "cities": ["Adoni", "Adyar"],
      "categories": ["Finance & Business"],
      "languages": ["Gujarati"],
      "platform": ["Instagram"]
    },
    "status": "approved",
    "service_type": "Photographers / Videographers",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": false,
    "is_deal_closed": false,
    "slug": "instagram finance & business photographers videographers adoni adyar 9e138f9d"
  },
  {
    "id_hash": "instagram-beauty-fashion-addanki-tamil-9e138f2fe78b415d93a3d7a26000fb83",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": false,
    "created_at": "2 weeks ago",
    "description": "Kdskjadkjsadknadclkasndifeoisafdkasfdiouaejfdckasdncaoisdhcasioudc",
    "request_details": {
      "cities": ["Addanki"],
      "categories": ["Beauty", "Fashion"],
      "languages": ["Tamil"],
      "platform": ["Instagram"]
    },
    "status": "approved",
    "service_type": "Talent Management Agencies",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": false,
    "is_deal_closed": false,
    "slug": "instagram beauty fashion addanki tamil 9e138f2f"
  },
  {
    "id_hash": "instagram-photographers-videographers-9e13850148ad45979b013df498a58e3b",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": false,
    "created_at": "2 weeks ago",
    "description": "Dslkfaslkdnfalksdnfaksdfsa;lkdfdaskdjnsakdsakjdnfa",
    "request_details": {
      "cities": ["Achhota"],
      "categories": ["Sports"],
      "languages": ["Marathi"],
      "platform": ["Instagram"]
    },
    "status": "approved",
    "service_type": "Photographers / Videographers",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": false,
    "is_deal_closed": false,
    "slug": "instagram photographers videographers 9e138501"
  },
  {
    "id_hash": "instagram-talent-management-agencies-9e13769e81f04de89488bff0076438a8",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": false,
    "created_at": "2 weeks ago",
    "description": "SjasdjlaslaksnxkaehdoaiejdaksdnaodjSAJALKSXMCLKSANX",
    "request_details": {
      "categories": ["Lifestyle", "Arts"],
      "platform": ["Instagram"]
    },
    "status": "approved",
    "service_type": "Talent Management Agencies",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": false,
    "is_deal_closed": false,
    "slug": "instagram talent management agencies 9e13769e"
  },
  {
    "id_hash": "instagram-general-marketing-services-9e1368b72601496da4016b22764c28a1",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": false,
    "created_at": "2 weeks ago",
    "description": "Ljadslkadlsakdjaskjdnakjsdakjsdkjsabdkjsbdkjbdskjdskjsdkjfabjdskjdfnsa",
    "request_details": {
      "platform": ["Instagram"]
    },
    "status": "approved",
    "service_type": "General Marketing Services",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": false,
    "is_deal_closed": false,
    "slug": "instagram general marketing services 9e1368b7"
  },
  {
    "id_hash": "xLb1EOP5",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": false,
    "created_at": "2 weeks ago",
    "description": "Avfjggsjgsvjh shikh shushk jhfsyh sjhfjh Sharjah hsvhs",
    "request_details": null,
    "status": "approved",
    "service_type": "Influencer Marketing Agencies",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": false,
    "is_deal_closed": false,
    "slug": "xLb1EOP5"
  },
  {
    "id_hash": "arts-general-marketing-services-chennai-9e13153ded194af795c20e7bdbdc186e",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": {
      "cities": ["Chennai"],
      "categories": ["Arts"]
    },
    "status": "approved",
    "service_type": "General Marketing Services",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "arts general marketing services chennai 9e13153d"
  },
  {
    "id_hash": "77PEV513",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": {
      "cities": ["Chennai"],
      "categories": ["Arts"]
    },
    "status": "approved",
    "service_type": "General Marketing Services",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "77PEV513"
  },
  {
    "id_hash": "photographers-/-videographers-9e1308de77a24cbabd0d434f07ba91a0",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": null,
    "status": "approved",
    "service_type": "Photographers / Videographers",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "photographers / videographers 9e1308de"
  },
  {
    "id_hash": "photographers-/-videographers-9e1308a35c214aa7a4b0dda0467e34ac",
    "user_details": {"name": "A Shashi’s", "profile_image": null, "company": "Abinash", "designation": "A"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": null,
    "status": "approved",
    "service_type": "Photographers / Videographers",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "photographers / videographers 9e1308a3"
  },
  {
    "id_hash": "instagram-arts-tech-chennai-english-9e13088e8475409994527afdba66adf1",
    "user_details": {"name": "Abiiii Nashnnn", "profile_image": null, "company": "Hashfame", "designation": "Software Engineer"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": {
      "cities": ["Chennai"],
      "followers_range": {"ig_followers_min": "1k", "ig_followers_max": "500k"},
      "categories": ["Arts", "Tech"],
      "languages": ["Hindi", "English", "Tamil", "Kannada", "Arabic"],
      "platform": ["Instagram"]
    },
    "status": "approved",
    "service_type": "Photographers / Videographers",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "instagram arts tech chennai english 9e13088e"
  },
  {
    "id_hash": "5k3D6MA2",
    "user_details": {"name": "Abiiii Nashnnn", "profile_image": null, "company": "Hashfame", "designation": "Software Engineer"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": {
      "cities": ["Chennai"],
      "followers_range": {"ig_followers_min": "1k", "ig_followers_max": "500k"},
      "categories": ["Arts", "Tech"],
      "languages": ["Hindi", "English", "Tamil", "Kannada", "Arabic"],
      "platform": ["Instagram"]
    },
    "status": "approved",
    "service_type": "Photographers / Videographers",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "5k3D6MA2"
  },
  {
    "id_hash": "instagram-arts-tech-chennai-english-9e10f5b3d7f04b5daaa4cff2316cb41b",
    "user_details": {"name": "Abiiii Nashnnn", "profile_image": null, "company": "Hashfame", "designation": "Software Engineer"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal saasdadsda",
    "request_details": {
      "cities": ["Chennai"],
      "followers_range": {"ig_followers_min": "1k", "ig_followers_max": "500k"},
      "categories": ["Arts", "Tech"],
      "languages": ["Hindi", "English", "Tamil", "Kannada", "Arabic"],
      "platform": ["Instagram"]
    },
    "status": "approved",
    "service_type": "General Marketing Services",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "instagram arts tech chennai english 9e10f5b3"
  },
  {
    "id_hash": "general-marketing-services-9e0aee60351d4a7287b0fb936da9f061",
    "user_details": {"name": "Abiiii Nashnnn", "profile_image": null, "company": "Hashfame", "designation": "Software Engineer"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": null,
    "status": "approved",
    "service_type": "General Marketing Services",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "general marketing services 9e0aee60"
  },
  {
    "id_hash": "-general-marketing-services-9e0aed7814ba47b995c492b7474f0c0b",
    "user_details": {"name": "Abiiii Nashnnn", "profile_image": null, "company": "Hashfame", "designation": "Software Engineer"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": null,
    "status": "approved",
    "service_type": "General Marketing Services",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": " general marketing services 9e0aed78"
  },
  {
    "id_hash": "instagram-general-marketing-services-9e0aed55d47942c5ae022b43e9805a38",
    "user_details": {"name": "Abiiii Nashnnn", "profile_image": null, "company": "Hashfame", "designation": "Software Engineer"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": {
      "followers_range": {"ig_followers_min": "1k", "ig_followers_max": "500k"},
      "platform": ["Instagram"]
    },
    "status": "approved",
    "service_type": "General Marketing Services",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "instagram general marketing services 9e0aed55"
  },
  {
    "id_hash": "instagram-youtube-arts-tech-chennai-english-9e0aebe30bac4dbe8db13409e7b9ebc1",
    "user_details": {"name": "Abiiii Nashnnn", "profile_image": null, "company": "Hashfame", "designation": "Software Engineer"},
    "is_high_value": true,
    "created_at": "2 weeks ago",
    "description": "Sample for testing. Reject this deal",
    "request_details": {
      "cities": ["Chennai"],
      "followers_range": {"ig_followers_min": "1k", "ig_followers_max": "500k", "yt_subscribers_min": "1k", "yt_subscribers_max": "100k"},
      "categories": ["Arts", "Tech"],
      "creator_count_min": 10,
      "creator_count_max": 100,
      "budget": "98,100",
      "brand": "HashFame",
      "languages": ["Hindi", "English", "Tamil", "Kannada", "Arabic"],
      "platform": ["Instagram", "YouTube"],
      "gender": "Male"
    },
    "status": "approved",
    "service_type": "General Marketing Services",
    "target_audience": "Agencies",
    "is_open": true,
    "is_pan_india": false,
    "any_language": true,
    "is_deal_closed": false,
    "slug": "instagram youtube arts tech chennai english 9e0aebe3"
  }
];
